package:
  name: declaracad
  version: 0.4.0dev

channels:
  - conda-forge
  - trelau
  - codelv

source:
  path: "../"

requirements:
  run:
  - pyocct
  pip:
    - PyQt5
    - PyQtWebEngine
    - enaml>=0.10.4
    - qtconsole
    - pyflakes
    - numpydoc
    - markdown
    - jsonpickle
    - QScintilla
    - enamlx
    - qt-reactor
    - pyserial
    - lxml
    - service_identity
    - pywin32 # os[win32]

build:
  number: 0
  noarch: python
  script:
    - pip install .
  entry_points:
    - declaracad = declaracad:main

test:
  imports:
    - declaracad.editor.plugin
    - declaracad.occ.occ_algo
    - declaracad.occ.qt.qt_occ_viewer

about:
  home: http://github.com/codelv/declaracad
  summary: "A declarative parametric 3D modeling application using python"
  license: GPLv3
