# This file is used to configure the AppVeyor CI system, for testing on Windows machines.
#
# Code based on https://github.com/nucleic/enaml/
#
# To test with AppVeyor:
#    Register on appveyor.com with your GitHub account.
#    Create a new appveyor project, using the GitHub details.
#    Ideally, configure notifications to post back to GitHub. (Untested)

branches:
  only:
    - master

environment:
    matrix:
        - NAME: "Py 3.6"
          MINICONDA: C:\Miniconda36-x64
          PYTHON_VERSION: "3.6"


install:
  # Activate conda env
  - call %MINICONDA%\Scripts\activate.bat

  - ECHO "Environment Variables"
  - set

  # Prepare Miniconda
  # - Avoid warning from conda info.
  # - Dump the setup for debugging.
  # - Upgrade to the latest version of pip to avoid it displaying warnings
  #   about it being out of date.
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Install python, conda build, and anaconda-client
  - conda install python=%PYTHON_VERSION% anaconda-client conda-build conda-verify -q

  # Install depencencies
  - conda install -c trelau -c conda-forge pyocct -q

  # Install testing utils
  - pip install pytest pytest-coverage pytest-qt codecov

# Use the script
build: off

build_script:

  - cd %APPVEYOR_BUILD_DIR%

  # Install declaracad
  - pip install -e .

  # Build the conda package
  # - conda build recipe -c conda-forge -c trelau -c codelv

test_script:

  # Run the project tests
  - cd %APPVEYOR_BUILD_DIR%
  - pytest tests -v --cov declaracad --cov-report xml

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

  # Build installer
  - constructor recipe

artifacts:
    - path: DeclaraCAD-*.exe
