# Created in DeclaraCAD
from math import sin, cos, radians
from declaracad.occ.api import *
inch = 25.4

enamldef Assembly(Part):
    attr thickness = 1/8 *inch 
    Box:
        display = False
        position = (-dx/2, -dy/2, 1.25*inch )
        color = 'purple'
        transparency = 0.6
        dx = 2*inch 
        dy = 2*inch 
        dz = 2*inch 
    Cut:
      Fuse:
        color = 'white'
        Cut:
          #transparency = 0.2
          ThickSolid:
            offset = thickness
            faces = [f for (i,f) in enumerate(body.topology.faces) if i in (1,3)]
            Fuse:   body:
                Cylinder: head:
                    radius = 1/2*inch  - thickness
                    height = 1*inch 
                    direction = (0, 0, 1)
                    position = (shaft.diameter+0.75*inch , 0, 1.5*inch )
                ThruSections:
                        solid = True
                        Wire:
                            Circle: c1:
                                radius << shaft.radius + 1/2*inch 
                                #direction = (1, 0, 0.5)
                        Wire:
                            Circle: c2:
                                direction = (0.2, 0, 1)
                                position = (0.1*inch , 0, 0.25*inch )
                                radius << c1.radius#+0.2
                        Wire:
                            Circle: c3:
                                direction = (0.2, 0, 0.5)
                                position = (1.25*inch , 0, 0.75*inch )
                                radius << head.radius*1.4
                        Wire:
                            Circle:  c4:
                                direction = head.direction
                                position = head.position
                                radius = head.radius
        Cylinder:
                radius = shaft.radius+thickness
                height = (3/4-1/8)*inch 
                position = (0, 0, 5/8*inch )                    
      Cylinder: shaft:
            attr diameter = 1*inch 
            transparency = 0.7
            radius = diameter/2
            height = 4 *inch 
    Looper:
        iterable = (c1, c2, c3, c4)
        Transform:
            display = False
            color = 'red'
            shape = loop.item
    
    Transform:
        display = False
        transparency = 0.7
        material = 'steel'
        shape = shaft
    #Transform:
    #    shape = c2
    #Transform:
    #    shape = c3

